In [2]:
import pandas as pd
data = pd.read_csv("parsed_json/word2vec-data.csv")

In [98]:
data.head()
# c = data['ethnicity'].isna()
# print(c.value_counts())

hair   eyes true_answer    FaceID   question ethnicity  gender       wv1  \
0  blond  brown         yes  IMG_9891  hair long     white  female -0.642567   
1  brown  brown         yes  IMG_0153  hair long     white  female -0.642567   
2  brown  brown          no  IMG_0446  hair long     white  female -0.642567   
3  blond   blue          no  IMG_9484  hair long     white  female -0.642567   
4  brown  brown         yes  IMG_9846  hair long     white    male -0.642567   

        wv2       wv3    ...         wv91     wv92      wv93      wv94  \
0  2.687369  2.729621    ...    -1.724558  2.76788  3.896488  0.844199   
1  2.687369  2.729621    ...    -1.724558  2.76788  3.896488  0.844199   
2  2.687369  2.729621    ...    -1.724558  2.76788  3.896488  0.844199   
3  2.687369  2.729621    ...    -1.724558  2.76788  3.896488  0.844199   
4  2.687369  2.729621    ...    -1.724558  2.76788  3.896488  0.844199   

       wv95      wv96      wv97      wv98      wv99     wv100  
0  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
1  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
2  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
3  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
4  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  

[5 rows x 107 columns]

In [3]:
df = data.drop(columns = ['question', 'FaceID'])
df = df.astype('category')
df['true_answer'] = df['true_answer'].cat.codes
df['gender'] = df['gender'].cat.codes
df['hair'] = df['hair'].cat.codes
df['eyes'] = df['eyes'].cat.codes
df['ethnicity'] = df['ethnicity'].cat.codes

In [4]:
# print(df.dtypes)
df = pd.DataFrame(df, dtype = 'float')
df.head()

hair  eyes  true_answer  ethnicity  gender       wv1       wv2       wv3  \
0   1.0   1.0          1.0        2.0     0.0 -0.642567  2.687369  2.729621   
1   3.0   1.0          1.0        2.0     0.0 -0.642567  2.687369  2.729621   
2   3.0   1.0          0.0        2.0     0.0 -0.642567  2.687369  2.729621   
3   1.0   0.0          0.0        2.0     0.0 -0.642567  2.687369  2.729621   
4   3.0   1.0          1.0        2.0     1.0 -0.642567  2.687369  2.729621   

        wv4      wv5    ...         wv91     wv92      wv93      wv94  \
0 -0.378051  1.19084    ...    -1.724558  2.76788  3.896488  0.844199   
1 -0.378051  1.19084    ...    -1.724558  2.76788  3.896488  0.844199   
2 -0.378051  1.19084    ...    -1.724558  2.76788  3.896488  0.844199   
3 -0.378051  1.19084    ...    -1.724558  2.76788  3.896488  0.844199   
4 -0.378051  1.19084    ...    -1.724558  2.76788  3.896488  0.844199   

       wv95      wv96      wv97      wv98      wv99     wv100  
0  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
1  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
2  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
3  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  
4  1.424915 -3.754926  1.074339 -2.414022 -1.031057  0.111689  

[5 rows x 105 columns]

In [88]:
df['true_answer'].value_counts()

0    169222
1    134634
Name: true_answer, dtype: int64

# Logicistic Regression

In [82]:
y = df["true_answer"]
X = df.drop(columns = ["true_answer"])

In [21]:
#train set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
        train_test_split(X, y, test_size=0.2, random_state= 0)

In [22]:
from sklearn.linear_model import LogisticRegression 
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_test = lr.predict(X_test)

In [25]:
y_baseline = [y.value_counts()[:1].index[0]] * len(y)
from sklearn.metrics import classification_report 
print(classification_report(y, y_baseline))

             precision    recall  f1-score   support

          0       0.56      1.00      0.72    169222
          1       0.00      0.00      0.00    134634

avg / total       0.31      0.56      0.40    303856



/Users/zeynep/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [28]:
from sklearn.metrics import mean_squared_error 
import numpy as np
y_pred = lr.predict(X_test)
# rmse_model = np.sqrt(mean_squared_error(y_test, y_pred))
# rmse_model


In [29]:
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix(y_test, y_pred)
print("a) Confusion matrix:\n%s" % confusionMatrix)

a) Confusion matrix:
[[50864     0]
 [    0  9908]]


In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 42)
logreg = LogisticRegression()
logreg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [32]:
y_pred = logreg.predict(X_test)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.57


In [33]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[29369  4332]
 [22073  4998]]


# k-Nearest Neighbours

In [40]:
y = df["true_answer"]
X = df.drop(columns = ["true_answer"])

In [49]:
# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2) # 70% training and 30% test

In [50]:
#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

#Create KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)

In [51]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6543967616665569


In [52]:
#Create KNN Classifier with 7 neighbors
knn = KNeighborsClassifier(n_neighbors=7)

#Train the model using the training sets
knn.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = knn.predict(X_test)
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6523398933719476


In [55]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)
#confusion_matrix.sum()

[[24627  9315]
 [11813 15017]]


# Random Forest

In [6]:
y = df["true_answer"]
X = df.drop(columns = ["true_answer"])

In [7]:
# Using Skicit-learn to split data into training and testing sets
#train set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
        train_test_split(X, y, test_size=0.2)

In [138]:
from sklearn.ensemble import RandomForestClassifier
from math import sqrt
#Create a Gaussian Classifier
clf=RandomForestClassifier(max_features = 10)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [132]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.6717402751267031


In [148]:
print(X.columns)

Index(['hair', 'eyes', 'ethnicity', 'gender', 'wv1', 'wv2', 'wv3', 'wv4',
       'wv5', 'wv6',
       ...
       'wv91', 'wv92', 'wv93', 'wv94', 'wv95', 'wv96', 'wv97', 'wv98', 'wv99',
       'wv100'],
      dtype='object', length=104)


In [152]:
import pandas as pd
feature_imp = pd.Series(clf.feature_importances_,index=X.columns).sort_values(ascending=False)
feature_imp

hair         0.134005
eyes         0.121220
gender       0.112236
ethnicity    0.093987
wv53         0.013327
wv100        0.011098
wv87         0.008552
wv55         0.008132
wv13         0.008120
wv84         0.008014
wv16         0.007762
wv60         0.007757
wv40         0.007525
wv42         0.007417
wv34         0.007304
wv94         0.007293
wv36         0.007101
wv81         0.007072
wv70         0.006804
wv26         0.006708
wv15         0.006460
wv8          0.006411
wv39         0.006312
wv85         0.006292
wv43         0.006206
wv67         0.006108
wv5          0.006087
wv54         0.006045
wv61         0.006035
wv78         0.005981
               ...   
wv65         0.004496
wv37         0.004493
wv74         0.004457
wv30         0.004439
wv79         0.004416
wv58         0.004409
wv89         0.004402
wv23         0.004391
wv52         0.004343
wv73         0.004322
wv28         0.004304
wv17         0.004281
wv75         0.004266
wv7          0.004258
wv29      

In [174]:
X = df[['hair','eyes','ethnicity','gender', 'wv53','wv100']]
y = df['true_answer']

In [175]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
        train_test_split(X, y, test_size=0.2)

In [179]:
from sklearn.ensemble import RandomForestClassifier
from math import sqrt
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [180]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.657671295991575


# Support Vector Machines

In [ ]:
#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='rbf') # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

In [ ]:
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))